### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by REMOOO** [brblacky/WaveMusic#12]
When i turn on autoplay and use leave cmd, it give me a error in this line
![Capture](https://user-images.githubusercontent.com/13511097/170798295-103285ed-362b-417e-9cba-f368ccedb5b0.PNG)

**Comment by REMOOO** [comment]
@brblacky [brblacky](https://github.com/brblacky)

**Comment by Venom9718** [comment]
Replace your old code in playerDestroy.js (line 9) with this:

```js
if (player.data.get("autoplay")) try { player.data.delete("autoplay") } catch (err) { client.logger.log(err.stack ? err.stack : err, "log") };
```
