### ISSUE TITLE
Remove command 

### ISSUE THREAD

**Issue by Barra203** [brblacky/WaveMusic#16]
remove command. when I remove the 1st track another song got removed to 
example: ">remove 1" songs number 2, 3, 4, etc also deleted

https://user-images.githubusercontent.com/102669079/174442566-631c6c5f-42b0-469c-a88d-435b21a98bf5.mp4

**Comment by Rstacx** [comment]
Remove command problem

**Comment by MJ1532** [comment]
@Barra203 if your issue is solved, please close this issues
