### ISSUE TITLE
Very strange bug

### ISSUE THREAD

**Issue by SammyTV** [brblacky/WaveMusic#19]
**Describe the bug**
When i try to play a song the bot responds with An unexcepted error occured. , and in the consle this pops up

**To Reproduce**

**Expected behavior**
Play music :) 

**Screenshots**
![image](https://user-images.githubusercontent.com/93628901/179134161-93b64d03-ce4d-422d-a956-ba2379275823.png)

**Desktop (please complete the following information):**
 - OS:win 11 [e.g. iOS]
 - Browser: brave [e.g. chrome, safari]
 - Version: I don't know [e.g. 22]

**Comment by parasop** [comment]
Error coming from kazagumo

**Comment by SammyTV** [comment]
yep i did try to reinstall no work

**Comment by Killerjet101** [comment]
I downgraded my node to v17.9.1 and it now works, so give that a shot
