### ISSUE TITLE
<rejected> DiscordAPIError: Invalid Form Body   components[0].components[0].url: A url is required

### ISSUE THREAD

**Issue by Seunghalee14** [brblacky/WaveMusic#2]
when using ABOUT HELP etc. This error occurs

<rejected> DiscordAPIError: Invalid Form Body
  components[0].components[0].url: A url is required

**Comment by AkAbhijit** [comment]
in message command or slash

**Comment by Seunghalee14** [comment]
What do you mean?

**Comment by brblacky** [comment]
Put invite link in config.js

**Comment by Seunghalee14** [comment]
I understand thanks
