### ISSUE TITLE
Song is not getting played

### ISSUE THREAD

**Issue by Moon29924** [brblacky/WaveMusic#38]
![Screenshot_2023-04-11-13-14-28-348_com android chrome](https://user-images.githubusercontent.com/130442448/231091419-94d94756-fcd8-45b3-b905-1ddfdc7ff0fc.png)

**Comment by ALMER789** [comment]
the same problem happened with with me
> [ERROR] Player Get exception [object Object]

**Comment by needhamgary** [comment]
@Moon29924 please post your issues in form of code blocks rather than images. Some images won't load in GitHub app.

**Comment by akshaytyagi482** [comment]
[03-05-2023 06:33:40]: [ERROR] Player Get exception [object Object]
it shows this in console whenever i try to a play a song by any method like /play or from the music system it joins the vc and just after that it leave the vc without playing anything

**Comment by needhamgary** [comment]
@akshaytyagi482 try changing to a different node. That was my problem. https://discord.com/channels/942117923001098260/942120035068018708/1085992650747945010 refer to this message, it worked best for me.

**Comment by akshaytyagi482** [comment]
the message link not opening can u send the message here or on my discord Pikachu®#9906 i shall be obliged

**Comment by needhamgary** [comment]
![image](https://user-images.githubusercontent.com/23411307/236155258-9b7fbad0-db76-4709-8d3b-52b8c028c43a.png)
try changing your Node to one of these @akshaytyagi482

**Comment by needhamgary** [comment]
@Moon29924 if your issue is resolved, please close.
