### ISSUE TITLE
Enhancing WaveMusic Discord Bot: User Feedback and Feature Suggestions

### ISSUE THREAD

**Issue by pigjustin** [brblacky/WaveMusic#49]
The default volume of the BOT is set to 100%. For some Discord newcomers, the volume can be too loud and uncomfortable when they join a voice channel. However, they usually don't change the volume of the BOT user immediately. I would like to request the addition of a parameter command that would allow me to modify the default volume in the documentation.

By the way, regarding some ongoing operational errors (BUGs), there are instances when the BOT doesn't clear messages in the text channels. This results in the accumulation of numerous and cluttered messages in the text channels.

Oh, one more thing! The interactive buttons provided by the author are indeed very useful. Currently, there are: (Decrease Volume), (Previous Song), (Pause), (Next Song), (Increase Volume), a total of 5 buttons. I hope there could be more added, such as: (Repeat Playback), (Shuffle Playback), (Request BOT to display the current playlist)...

If these could be implemented, it would be truly perfect!!

**Comment by BallavaNarayan** [comment]
@pigjustin Regarding your 2nd Point do want to auto delete the User Command Messages also or just the bot replies ??

**Comment by pigjustin** [comment]
> @pigjustin Regarding your 2nd Point do want to auto delete the User Command Messages also or just the bot replies ??

I've created a dedicated text chat channel for members in my Discord. Typically, this channel serves as a space for interactive conversations among Discord members. Concurrently, we also have a separate WaveMusic channel exclusively for music playback. These two channels are distinct, and it's widely understood that the WaveMusic channel is designated specifically for playing music.

Given this context, I hope to maintain a neat and uncluttered environment within the WaveMusic channel. My suggestion involves enabling the BOT to automatically clear user command requests after a certain period, say 5 minutes (equivalent to 300 seconds), including messages like /ping, /nowplaying, and similar commands.

I believe implementing this enhancement could further elevate the overall user experience in the WaveMusic channel, allowing each member to immerse themselves more fully in music playback. I genuinely appreciate your attentive consideration and understanding.

Thank you so much!

**Comment by BallavaNarayan** [comment]
@pigjustin Please test PR #51 and let me what else improvement can be done..

**Comment by pigjustin** [comment]
I reinstalled and tested the default volume command, but there was no response, and the automatic deletion part also didn't work.

**Comment by pigjustin** [comment]
> @pigjustin請測試 PR #51，讓我看看還有哪些可以改進的地方。

I reinstalled and tested the default volume command, but there was no response, and the automatic deletion part also didn't work.

**Comment by pigjustin** [comment]
> @pigjustin你收到任何錯誤嗎？？？

No error message appeared when I used the "defaultVolume" command, but there was no response.

**Comment by BallavaNarayan** [comment]
I will suggest try this one [Wave](https://github.com/BallavaNarayan/WaveMusic) .

**Comment by pigjustin** [comment]
> I will suggest try this one [Wave](https://github.com/BallavaNarayan/WaveMusic) .

Currently, after the installation, it appears to be working fine. I'll have my friends test it for a while to see if there are any other issues, and I'll get back to you. Thank you.
